name: CI
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and package
        run: |
          # 执行打包操作，生成 dist 文件夹
          npm install
          npm run build
          tar czf dist.tar.gz dist

      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: "cherish"
          password: ${{ secrets.PRIVATE_KEY }}
          source: './dist.tar.gz'
          target: ${{ secrets.PATH }}

      - name: SSH to server and extract files
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: "cherish"
          password: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd ${{ secrets.PATH }}
            tar xzf dist.tar.gz
            rm dist.tar.gz
